retargeting:
  type: DexPilot
  urdf_path: xhand/xhand_right.urdf

  # Target refers to the retargeting target, which is the robot hand
  wrist_link_name: "base_link"
  finger_tip_link_names: [ "right_hand_thumb_rota_tip", "right_hand_index_rota_tip", "right_hand_mid_tip", "right_hand_ring_tip", "right_hand_pinky_tip" ]
  scaling_factor: 1.0

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  low_pass_alpha: 0.2
