# Version 1.0, 2025-07-10
# Author: Lai Wei

retargeting:
  type: DexPilot
  urdf_path: xhand/xhand_right.urdf

  # Target refers to the retargeting target, which is the robot hand
  target_joint_names: ['right_hand_thumb_bend_joint',
                      'right_hand_thumb_rota_joint1',
                      'right_hand_thumb_rota_joint2',
                      'right_hand_index_bend_joint',
                      'right_hand_index_joint1',
                      'right_hand_index_joint2',
                      'right_hand_mid_joint1',
                      'right_hand_mid_joint2',
                      'right_hand_ring_joint1',
                      'right_hand_ring_joint2',
                      'right_hand_pinky_joint1',
                      'right_hand_pinky_joint2']
  wrist_link_name: "base_link"
  finger_tip_link_names: [ "right_hand_thumb_rota_tip",  "right_hand_index_rota_tip", 
                           "right_hand_mid_tip", "right_hand_ring_tip", "right_hand_pinky_tip" ]
  scaling_factor: 1.05

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  low_pass_alpha: 0.5
  project_dist: 0.008
  escape_dist: 0.01
